{% set name = "liquid" %}
{% set version = "5.0.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 745771f725b8f6541c4ed942755cb43b7b8d7bb4d4ab9437ba074cebd95772d8

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: A secure, non-evaling end user template engine with aesthetic markup.

  doc_url: http://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/shopify/{{ name }}

extra:
  recipe-maintainers:
    - sodre
