travis:
  secure:
    BINSTAR_TOKEN: bpJx+a/d6t9Hur0tv6RJWB+iGfAJ3fwl/C3GFHVsoyXQgfwMa9HfBO/48IXdXR1Hw+jLGK8HyRSs7A2NFOHQomDncej+Mmzt782n6hm3lHYW+Jdl7UB825SbOE1uYqn3fR4Z/8YPJjBiuX8oPczcrG5CEVNvCwcj+DQly6HDYVdOP0htbs0qqJIvVm3VlIZGGPFedzx5ESq8eCcWmHJiVXp6QAOf2I/82Qv9pbf1wzCo06o2+rNFbUJ8blwGQU7hsAO9FboJVHoK1NpfeSvIG5lZfTci6C87fkIHKHG92AkcVpLfzHz6G4Ml5vM55rfOiH0AclUHBPuYO+reuHEaDOQ/h0DNNaw0XomD8XpSYGLVVKejPTV3K7WLUABPb82xh65OV5sdTf5uBqsd4iRZxLkbpxFpXJTvnH1Q0INspwmzqJ0dxJzv94hMuRhDjFaj0wlXu161zpELJzbUTLUlKu9zLMcaH/0y8GuERRXUahTKY7L3XkcIO5vlx8N8+n+5ft5Vt+JMgqg2eQO85ieEI8xut77sm9O93Nx5NF1DJmos+GNmxOJl8nYRigFvulv0Z0FXPkwoWfOfZ4x9PgDaV8/RpCq5cvh5M/vaOui5WszObE49j+jibHqoolomLoV/gbsStRq0cwoqjJRCg8//ygVMeA3D8m/EHHnW7RXzbcU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
